[project]
name = "cold-start-backend"
version = "0.1.0"
description = "Backend for cold-start recommendation system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.29.0",
    "fastapi[standard]>=0.115.0",
    "rutube-cold-start>=1.1.5",
    "sqlalchemy>=2.0.35",
]
